### ISSUE TITLE
"scriptit" is an option when selecting which modality to work with 

### ISSUE THREAD

**Issue by karkantar** [josephdviviano/scriptuit#5]
<img width="520" alt="screen shot 2016-08-15 at 10 46 28 am" src="https://cloud.githubusercontent.com/assets/20997115/17668034/8a912da0-62d5-11e6-8f7f-aa36a0908fc1.png">

**Comment by josephdviviano** [comment]
I can't seem to reproduce this. Do you have a folder name 'script-it' in one of the subject's folders?
