### ISSUE TITLE
render masterscript command isn't working

### ISSUE THREAD

**Issue by karkantar** [josephdviviano/scriptuit#6]
tried various versions of typing the command, including the way specified in the manual and the way it is listed with scriptit help and either scriptit help list comes up again or given various errors. 
Tried different possible versions of the command in the directory where the master script is located and in the directory to which the scriptit paths point to.

**Some examples of errors:**

Traceback (most recent call last):
  File "/srv/CODE/script-it/bin/scriptit", line 512, in <module>
    render(sys.argv[2], sys.argv[3])
  File "/srv/CODE/script-it/bin/scriptit", line 368, in render
    masterData, foundModules = parse_master(script)
  File "/srv/CODE/script-it/bin/scriptit", line 258, in parse_master
    masterData = [line.replace('=', ' ').rstrip() for line in open(script, 'rb')]
IOError: [Errno 2] No such file or directory: 'script'
karkan@Harford:/srv/CODE/epitome/modules$ scriptit render script master_160824_PRELIMscripit.sh
Traceback (most recent call last):
  File "/srv/CODE/script-it/bin/scriptit", line 512, in <module>
    render(sys.argv[2], sys.argv[3])
  File "/srv/CODE/script-it/bin/scriptit", line 368, in render
    masterData, foundModules = parse_master(script)
  File "/srv/CODE/script-it/bin/scriptit", line 258, in parse_master
    masterData = [line.replace('=', ' ').rstrip() for line in open(script, 'rb')]
IOError: [Errno 2] No such file or directory: 'script'
karkan@Harford:/srv/CODE/epitome/modules$ scriptit render master script master_160824_PRELIMscripit.sh

**another error using a different variation of the command:**
File "/srv/CODE/script-it/bin/scriptit", line 512, in <module>
    render(sys.argv[2], sys.argv[3])
  File "/srv/CODE/script-it/bin/scriptit", line 368, in render
    masterData, foundModules = parse_master(script)
  File "/srv/CODE/script-it/bin/scriptit", line 258, in parse_master
    masterData = [line.replace('=', ' ').rstrip() for line in open(script, 'rb')]
IOError: [Errno 2] No such file or directory: 'script'
karkan@Harford:/srv/MRI/WORKING/KAR$ scriptit render

**Comment by josephdviviano** [comment]
hey @karkantar are you just running this

```
scriptit render
```

it should be

```
scriptit render some-master-script.sh
```

**Comment by karkantar** [comment]
no I’ve been running the latter command, I’ve tried a bunch of different variations of the command last friday, but ill try right now again just to see if anything’s changed

**Comment by josephdviviano** [comment]
try this:

```
scriptit render master_160824_PRELIMscripit.sh
```

**Comment by karkantar** [comment]
Yeah I did that several times and this is what I get

**Comment by karkantar** [comment]
it just gives me the list of scriptit commands 

<img width="624" alt="screen shot 2016-09-07 at 5 31 10 pm" src="https://cloud.githubusercontent.com/assets/20997115/18329373/15583570-7521-11e6-98ca-2121b66e3186.png">

**Comment by josephdviviano** [comment]
oh my bad, try this:

```
scriptit render master_160824_PRELIMscripit.sh preproc.sh
```

your output should be `preproc.sh`

**Comment by karkantar** [comment]
yup great! that worked, thanks

**Comment by josephdviviano** [comment]
welcome!
